modLoader = "javafml"
loaderVersion = "[1,)"
license = "CC-BY-NC-ND-4.0"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
description = "Server-side XP pickup smoothing that keeps the vanilla orb feel."
authors = ["Jeff E"]
license = "CC-BY-NC-ND-4.0"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "xp_stream.neoforge.mixins.json"
environment = "*"

